/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnnualRecord {
  'yearLabel' : string,
  'coffeeIncome' : bigint,
  'pepperIncome' : bigint,
  'arecanutIncome' : bigint,
  'paddyIncome' : bigint,
  'fertilisers' : bigint,
  'irrigation' : bigint,
  'managerSalary' : bigint,
  'workersTotalSalary' : bigint,
  'miscellaneous' : bigint,
}
export interface Equipment {
  'id' : bigint,
  'purchaseDate' : string,
  'cost' : bigint,
  'name' : string,
  'equipmentType' : string,
  'notes' : string,
  'condition' : string,
}
export interface SalaryRecord {
  'id' : bigint,
  'month' : bigint,
  'workerId' : bigint,
  'paid' : boolean,
  'year' : bigint,
  'amount' : bigint,
}
export interface Summary {
  'equipmentCount' : bigint,
  'totalDebits' : bigint,
  'totalSalaryPaid' : bigint,
  'totalEquipmentCost' : bigint,
  'netProfitLoss' : bigint,
  'totalCredits' : bigint,
  'workerCount' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'date' : string,
  'description' : string,
  'category' : string,
  'txType' : TxType,
  'amount' : bigint,
}
export type TxType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'id' : bigint,
  'joinDate' : string,
  'name' : string,
  'role' : string,
  'phone' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEquipment' : ActorMethod<
    [string, string, string, bigint, string, string],
    bigint
  >,
  'addSalary' : ActorMethod<[bigint, bigint, bigint, bigint, boolean], bigint>,
  'addTransaction' : ActorMethod<
    [TxType, string, bigint, string, string],
    bigint
  >,
  'addWorker' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEquipment' : ActorMethod<[bigint], boolean>,
  'deleteSalary' : ActorMethod<[bigint], boolean>,
  'deleteTransaction' : ActorMethod<[bigint], boolean>,
  'deleteWorker' : ActorMethod<[bigint], boolean>,
  'getAllAnnualRecords' : ActorMethod<[], Array<AnnualRecord>>,
  'getAnnualRecord' : ActorMethod<[string], [] | [AnnualRecord]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEquipment' : ActorMethod<[], Array<Equipment>>,
  'getSalaries' : ActorMethod<[], Array<SalaryRecord>>,
  'getSummary' : ActorMethod<[], Summary>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAnnualRecord' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEquipment' : ActorMethod<
    [bigint, string, string, string, bigint, string, string],
    boolean
  >,
  'updateSalary' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, boolean],
    boolean
  >,
  'updateTransaction' : ActorMethod<
    [bigint, TxType, string, bigint, string, string],
    boolean
  >,
  'updateWorker' : ActorMethod<
    [bigint, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
