/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnualRecord = IDL.Record({
  'yearLabel' : IDL.Text,
  'coffeeIncome' : IDL.Nat,
  'pepperIncome' : IDL.Nat,
  'arecanutIncome' : IDL.Nat,
  'paddyIncome' : IDL.Nat,
  'fertilisers' : IDL.Nat,
  'irrigation' : IDL.Nat,
  'managerSalary' : IDL.Nat,
  'workersTotalSalary' : IDL.Nat,
  'miscellaneous' : IDL.Nat,
});
export const TxType = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Equipment = IDL.Record({
  'id' : IDL.Nat,
  'purchaseDate' : IDL.Text,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'equipmentType' : IDL.Text,
  'notes' : IDL.Text,
  'condition' : IDL.Text,
});
export const SalaryRecord = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'workerId' : IDL.Nat,
  'paid' : IDL.Bool,
  'year' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Summary = IDL.Record({
  'equipmentCount' : IDL.Nat,
  'totalDebits' : IDL.Int,
  'totalSalaryPaid' : IDL.Int,
  'totalEquipmentCost' : IDL.Int,
  'netProfitLoss' : IDL.Int,
  'totalCredits' : IDL.Int,
  'workerCount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'txType' : TxType,
  'amount' : IDL.Nat,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEquipment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [TxType, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSalary' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllAnnualRecords' : IDL.Func([], [IDL.Vec(AnnualRecord)], ['query']),
  'getAnnualRecord' : IDL.Func([IDL.Text], [IDL.Opt(AnnualRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getSalaries' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnnualRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEquipment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, TxType, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateWorker' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnualRecord = IDL.Record({
    'yearLabel' : IDL.Text,
    'coffeeIncome' : IDL.Nat,
    'pepperIncome' : IDL.Nat,
    'arecanutIncome' : IDL.Nat,
    'paddyIncome' : IDL.Nat,
    'fertilisers' : IDL.Nat,
    'irrigation' : IDL.Nat,
    'managerSalary' : IDL.Nat,
    'workersTotalSalary' : IDL.Nat,
    'miscellaneous' : IDL.Nat,
  });
  const TxType = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Equipment = IDL.Record({
    'id' : IDL.Nat,
    'purchaseDate' : IDL.Text,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'equipmentType' : IDL.Text,
    'notes' : IDL.Text,
    'condition' : IDL.Text,
  });
  const SalaryRecord = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'workerId' : IDL.Nat,
    'paid' : IDL.Bool,
    'year' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Summary = IDL.Record({
    'equipmentCount' : IDL.Nat,
    'totalDebits' : IDL.Int,
    'totalSalaryPaid' : IDL.Int,
    'totalEquipmentCost' : IDL.Int,
    'netProfitLoss' : IDL.Int,
    'totalCredits' : IDL.Int,
    'workerCount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEquipment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [TxType, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSalary' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllAnnualRecords' : IDL.Func([], [IDL.Vec(AnnualRecord)], ['query']),
    'getAnnualRecord' : IDL.Func([IDL.Text], [IDL.Opt(AnnualRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getSalaries' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnnualRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEquipment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, TxType, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateWorker' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
