/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
import type { AnnualRecord, AnnualExtras, IncomeItem, ExpenseItem } from "./backend.d";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SalaryRecord {
    id: bigint;
    month: bigint;
    workerId: bigint;
    paid: boolean;
    year: bigint;
    amount: bigint;
}
export interface Summary {
    equipmentCount: bigint;
    totalDebits: bigint;
    totalSalaryPaid: bigint;
    totalEquipmentCost: bigint;
    netProfitLoss: bigint;
    totalCredits: bigint;
    workerCount: bigint;
}
export interface Equipment {
    id: bigint;
    purchaseDate: string;
    cost: bigint;
    name: string;
    equipmentType: string;
    notes: string;
    condition: string;
}
export interface Worker {
    id: bigint;
    joinDate: string;
    name: string;
    role: string;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    id: bigint;
    date: string;
    description: string;
    category: string;
    txType: TxType;
    amount: bigint;
}
export enum TxType {
    credit = "credit",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEquipment(name: string, equipmentType: string, purchaseDate: string, cost: bigint, condition: string, notes: string): Promise<bigint>;
    addSalary(workerId: bigint, month: bigint, year: bigint, amount: bigint, paid: boolean): Promise<bigint>;
    addTransaction(txType: TxType, category: string, amount: bigint, date: string, description: string): Promise<bigint>;
    addWorker(name: string, role: string, phone: string, joinDate: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEquipment(id: bigint): Promise<boolean>;
    deleteSalary(id: bigint): Promise<boolean>;
    deleteTransaction(id: bigint): Promise<boolean>;
    deleteWorker(id: bigint): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEquipment(): Promise<Array<Equipment>>;
    getSalaries(): Promise<Array<SalaryRecord>>;
    getSummary(): Promise<Summary>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkers(): Promise<Array<Worker>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEquipment(id: bigint, name: string, equipmentType: string, purchaseDate: string, cost: bigint, condition: string, notes: string): Promise<boolean>;
    updateSalary(id: bigint, workerId: bigint, month: bigint, year: bigint, amount: bigint, paid: boolean): Promise<boolean>;
    updateTransaction(id: bigint, txType: TxType, category: string, amount: bigint, date: string, description: string): Promise<boolean>;
    updateWorker(id: bigint, name: string, role: string, phone: string, joinDate: string): Promise<boolean>;
    addIncomeItem(yearLabel: string, name: string, amount: bigint): Promise<bigint>;
    deleteIncomeItem(id: bigint): Promise<boolean>;
    getIncomeItemsByYear(yearLabel: string): Promise<Array<IncomeItem>>;
    addExpenseItem(yearLabel: string, name: string, amount: bigint): Promise<bigint>;
    deleteExpenseItem(id: bigint): Promise<boolean>;
    getExpenseItemsByYear(yearLabel: string): Promise<Array<ExpenseItem>>;
}
import type { Transaction as _Transaction, TxType as _TxType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEquipment(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addSalary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalary(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalary(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTransaction(arg0: TxType, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TxType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TxType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addWorker(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorker(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorker(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEquipment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipment(arg0);
            return result;
        }
    }
    async deleteSalary(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalary(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async deleteWorker(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorker(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipment(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipment();
            return result;
        }
    }
    async getSalaries(): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaries();
            return result;
        }
    }
    async getSummary(): Promise<Summary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkers();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEquipment(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSalary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalary(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalary(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: TxType, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_TxType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_TxType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateWorker(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveAnnualRecord(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnnualRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnnualRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async getAllAnnualRecords(): Promise<Array<AnnualRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnualRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnualRecords();
            return result;
        }
    }
    async getAnnualRecord(arg0: string): Promise<AnnualRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualRecord(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualRecord(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async saveAnnualExtras(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnnualExtras(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnnualExtras(arg0, arg1, arg2);
            return result;
        }
    }
    async getAnnualExtras(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualExtras(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualExtras(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async addIncomeItem(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomeItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomeItem(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteIncomeItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncomeItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncomeItem(arg0);
            return result;
        }
    }
    async getIncomeItemsByYear(arg0: string): Promise<Array<IncomeItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeItemsByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeItemsByYear(arg0);
            return result;
        }
    }
    async addExpenseItem(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseItem(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteExpenseItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseItem(arg0);
            return result;
        }
    }
    async getExpenseItemsByYear(arg0: string): Promise<Array<ExpenseItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseItemsByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseItemsByYear(arg0);
            return result;
        }
    }
}
function from_candid_Transaction_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    description: string;
    category: string;
    txType: _TxType;
    amount: bigint;
}): {
    id: bigint;
    date: string;
    description: string;
    category: string;
    txType: TxType;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: value.category,
        txType: from_candid_TxType_n11(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TxType {
    return "credit" in value ? TxType.credit : "debit" in value ? TxType.debit : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n9(_uploadFile, _downloadFile, x));
}
function to_candid_TxType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): _TxType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): {
    credit: null;
} | {
    debit: null;
} {
    return value == TxType.credit ? {
        credit: null
    } : value == TxType.debit ? {
        debit: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
